#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html lang='en'>"
echo "<head>"
echo "    <meta charset='UTF-8'>"
echo "    <title>Hello Page</title>"
echo "</head>"
echo "<body>"
echo "    <h1>Hello from bash!</h1>"
echo "</body>"
echo "</html>"